### ISSUE TITLE
Board control announcement delayed

### ISSUE THREAD

**Issue by chrrisyg** [howardchung/jeopardy#51]
Recently the gridding will occasionally break. There will sometimes be a row that is empty save for one category, a row that is 4 categories and one dollar amount, 4 rows of dollar amounts that are shifted by one column, and one row that is empty save for one dollar amount. We also noticed that the voice is one round behind the game in saying who has the board (e.g. if person A has the board, person B answers correctly, it will say A still has the board despite the pointer being correct). I am not sure what causes the issue, but I have noticed it only recently and it happens to everyone in that lobby.

**Comment by howardchung** [comment]
If possible can you provide a game ID that reproduces this issue?

**Comment by howardchung** [comment]
As for some cells being occasionally empty--this happens if the game wasn't completely shown on TV

**Comment by chrrisyg** [comment]
> As for some cells being occasionally empty--this happens if the game wasn't completely shown on TV

Yeah, this is a different issue. I don't code much but it seems like an index being off by one, resulting in a game grid that is 8X6 with 12 cells open instead of 6X6 with no cells open. We played game # 8286 and 8287. If there was an update sometime in the last couple weeks, that might have done it?

**Comment by howardchung** [comment]
Did this happen in the jeopardy or Double Jeopardy round? Trying to repro with 8286

**Comment by howardchung** [comment]
And does it happen immediately or after several questions have been selected?

**Comment by chrrisyg** [comment]
It actually happened in both rounds, after some questions had been asked. It happened first with one category left in the first round, and in the second round it seemed to be more random. There were four in the lobby if that matters.

**Comment by howardchung** [comment]
OK I checked in a change and tested and it seems to have gone away? But can't consistently make it happen so just update this if you see it again

**Comment by chrrisyg** [comment]
Sounds good, thank you! I really like the game!

**Comment by chrrisyg** [comment]
Just wanted to note, not seeing the table format issue today but the voice is still one clue behind for who controls the board

**Comment by howardchung** [comment]
Fixed by deleting the next person annoucement--but I think I also identified the issue if we want to bring it back
