### ISSUE TITLE
Host mode/advanced settings dialog

### ISSUE THREAD

**Issue by howardchung** [howardchung/jeopardy#54]
Enable a special mode for a host to run living room games

Currently, living room games with many players should generally be run in Coryat mode(to let more than one person score, but this also disables DDs)

Ideally we find a way to have DDs but keep the "more than one person can score" behavior--maybe a new "host" mode that is basically Coryat with DDs?

The host should be:
* Permanent picker (but if we keep DDs they aren't eligible for DDs, so the person who got the last first correct answer should be the only person allowed to answer)
* Only person able to submit judge commands
* Ideally they should also be removed from the scoreboard, displayed elsewhere as "host", and not count towards waiting for players to buzz or pass, but less important

**Comment by jdonland** [comment]
Implementing an auto-pass mode would go a long way toward accommodating non-playing hosts.

**Comment by howardchung** [comment]
That would probably work pretty well for spectators (might also want to disable their ability to pick clues)

For hosts we would want to keep the ability to pick clues, but we also need to handle what happens if they pick a DD

**Comment by howardchung** [comment]
I think we could implement this using a "advanced settings" dialog that the user can choose from before starting the game.

If set, allow configuring the timeouts for wagers, answers, and final jeopardy
Also allow setting the game creator as host which means only they can do judging and picking questions_
