### ISSUE TITLE
New Games Not Working

### ISSUE THREAD

**Issue by spburstein** [howardchung/jeopardy#58]
Hello.

Recently, new jeopardy games have not been working. When I enter the show title the game board becomes a black screen, starting with game 8807. I know that there were recently some changes to J-Archive!, so maybe that has something to do with it. I am a big fan of this software and it has made playing jeopardy games with my friends significantly easier. Thank you.

**Comment by howardchung** [comment]
I refresh the games manually every few months--they are not immediately available for play after being aired.
