### ISSUE TITLE
Chat doesn't show up on the website

### ISSUE THREAD

**Issue by moataz985** [howardchung/jeopardy#63]
There is no longer a text field in which to type messages. Chat window is there but no input.

**Comment by howardchung** [comment]
I removed the chat feature as it didn't seem super useful and it was confusing users who were  typing their answers into it. The chat window is now a "game log" window.

Willing to revisit if there's strong demand but for me, I'm usually on an audio call with friends when playing

**Comment by moataz985** [comment]
I would appreciate it if you would consider readding this feature. Maybe add a separate tab for just the chat.

**Comment by howardchung** [comment]
Chat is back! I needed it for some feature testing, so it's back for now
