### ISSUE TITLE
Add Instructions to the application

### ISSUE THREAD

**Issue by chances** [howardchung/jeopardy#72]
We are unable to start a game after joining with three players. We are stuck on a black screen, Changing the game mode does nothing. Clicking on "Game#" does nothing. The chat box is empty. All we are able to do is set our player names and see them below the black screen.

![Screenshot from 2024-01-27 23-43-45](https://github.com/howardchung/jeopardy/assets/635049/a0869263-b024-4c26-9246-8e0030cef343)

Please add play instructions.

**Comment by howardchung** [comment]
To start a new game, click "new game" and pick a type of game to play
