### ISSUE TITLE
Able to load some game #s manually but not others?

### ISSUE THREAD

**Issue by inside-game** [howardchung/jeopardy#74]
Hi, when entering specific game numbers manually from the J-Archive site, the app seems to load some and not others. Not sure what the pattern or reason is. For example, trying any game from range 841-949 doesn't seem to load (but 840 and 950 do). Regardless of this minor detail, thank you for making this app - it is fantastic!

![game949](https://github.com/howardchung/jeopardy/assets/78992830/0e225882-ac66-45eb-9499-0a6a753f687e)

**Comment by howardchung** [comment]
Looks like we were missing some episodes from the data. I'm not sure if it was broken when I originally downloaded the data, or maybe J-Archive added it later. Either way I'm working on loading the missing episodes now, thanks for the catch!
